using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

// Rebuilds only the named enrichment groups. Original actors, route, giant tree,
// cameras and story settings are not regenerated by this authoring command.
public static class Chapter2ForestRichnessAuthoring
{
    const string Root = "Assets/Chapter2/Environment/RichForest/";
    const string ScenePath = "Assets/Scenes/第二章.unity";
    static System.Random random;
    static readonly Dictionary<Material, Material> converted = new Dictionary<Material, Material>();
    static Collider ground;
    static Transform scenery;
    static readonly List<Vector3> trunks = new List<Vector3>();
    static readonly Vector3[] homes = {
        new Vector3(-6.3f,0,-5.5f), new Vector3(6.1f,0,-1.6f), new Vector3(-7.3f,0,6),
        new Vector3(8.4f,0,10.8f), new Vector3(10.5f,0,-6.8f)
    };

    [MenuItem("Tools/Chapter 2/Enrich Forest and Background NPCs")]
    public static void Apply()
    {
        if (EditorApplication.isPlaying) throw new InvalidOperationException("Exit Play Mode first.");
        var c = Object.FindFirstObjectByType<Chapter2Controller>();
        if (!c || c.gameObject.scene.path != ScenePath) throw new InvalidOperationException("Open Chapter 2 first.");
        Directory.CreateDirectory(Root+"Materials"); Directory.CreateDirectory(Root+"Textures"); Directory.CreateDirectory(Root+"Geometry");
        AssetDatabase.Refresh();
        random = new System.Random(19301007); converted.Clear(); trunks.Clear();
        var old = GameObject.Find("Forest enrichment · layered woodland");
        if (old) Object.DestroyImmediate(old);
        var oldNPCs = c.dayGroup.transform.Find("Background people · local patrols");
        if (oldNPCs) Object.DestroyImmediate(oldNPCs.gameObject);
        scenery = new GameObject("Forest enrichment · layered woodland").transform;
        ground = GameObject.Find("Forest ground").GetComponent<Collider>();
        Physics.SyncTransforms();
        BuildGround(c);
        AddTrees();
        AddPlants();
        AddForestDebris();
        AddPeople(c);
        EditorSceneManager.MarkSceneDirty(c.gameObject.scene);
        AssetDatabase.SaveAssets(); EditorSceneManager.SaveScene(c.gameObject.scene);
        Debug.Log("[Chapter2 forest] Enrichment saved: " + trunks.Count + " trees, 5 local NPCs, layered ground and clustered undergrowth.");
    }

    static void BuildGround(Chapter2Controller c)
    {
        var shader = Shader.Find("Chapter2/Layered Forest Ground");
        if (!shader) throw new InvalidOperationException("Forest shader has not imported.");
        var m = MaterialAsset("Layered woodland earth", shader);
        string ph = "Assets/Chapter2/Environment/PolyHaven/";
        m.SetTexture("_BaseMap", Texture(ph+"forest_floor_diff_4k.jpg",false));
        m.SetTexture("_LeafNormal", Texture(ph+"forest_floor_nor_gl_4k.jpg",true));
        m.SetTexture("_LeafAO", Texture(ph+"forest_floor_ao_4k.jpg",false));
        m.SetTexture("_SoilMap", Texture(Root+"Textures/brown_mud_diff_2k.jpg",false));
        m.SetTexture("_SoilNormal", Texture(Root+"Textures/brown_mud_nor_gl_2k.jpg",true));
        m.SetTexture("_SoilAO", Texture(Root+"Textures/brown_mud_ao_2k.jpg",false));
        m.SetTexture("_SoilRoughness", Texture(Root+"Textures/brown_mud_rough_2k.jpg",false));
        m.SetTexture("_MossMap", Texture("Assets/Realistic Terrain Collection/Other/Textures/ForestFloor2/forest_floor_2.jpg",false));
        m.SetTexture("_MossNormal", Texture("Assets/Realistic Terrain Collection/Other/Textures/ForestFloor2/forest_floor_2_normal.png",true));
        m.SetFloat("_LeafScale",2.25f);m.SetFloat("_SoilScale",2.3f);m.SetFloat("_MossScale",1.65f);
        m.SetFloat("_NormalStrength",.8f);
        m.SetColor("_LeafTint",new Color(.8f,.78f,.7f));
        m.SetColor("_SoilTint",new Color(.96f,.91f,.81f));
        m.SetColor("_MossTint",new Color(.62f,.67f,.49f));
        EditorUtility.SetDirty(m);
        var detail=c.dayGroup.GetComponent<Chapter2ForestDetail>();
        detail.detailedFloor=m;
        // Show the same ground in Edit Mode; the layered shader also responds to the night firelight.
        detail.ground.sharedMaterial=m;
    }

    static void AddTrees()
    {
        var parent=Group("Trees · intermediate canopy",scenery);
        // Deliberate framing trees and NPC shade trees, followed by irregular midground groups.
        var positions=new List<Vector3>{
            new Vector3(-6.8f,0,-8),new Vector3(6.7f,0,-6),new Vector3(-8.8f,0,.5f),
            new Vector3(8.8f,0,3.5f),new Vector3(-8.5f,0,9),new Vector3(10,0,12.3f),
            new Vector3(-5.7f,0,17.5f),new Vector3(7.5f,0,18.5f)
        };
        int attempts=0;
        while(positions.Count<38 && attempts++<1000)
        {
            float side=positions.Count%2==0?-1:1;
            var p=new Vector3(side*Range(9,27),0,Range(-17,30));
            if(positions.Any(t=>Vector3.Distance(t,p)<3.7f))continue;
            positions.Add(p);
        }
        for(int i=0;i<positions.Count;i++)
        {
            var p=positions[i];
            string path=i>=8&&i%4==0?"Assets/Hipernt/Pine Pack/Prefabs/Pine"+(1+i%6)+".prefab":"Assets/樹/綠樹.prefab";
            float height=i<8?Range(10,14.5f):Range(11,21);
            var tree=Place(path,"Grove tree "+(i+1),parent,p,height);
            trunks.Add(p);
            // Colliders represent trunks only; positions stay outside the play corridor.
            var collider=new GameObject("Trunk collision").AddComponent<CapsuleCollider>();
            collider.transform.SetParent(parent,false);collider.transform.position=new Vector3(p.x,GroundY(p),p.z);
            collider.height=height*.65f;collider.radius=.22f;collider.center=Vector3.up*collider.height*.5f;
            // Reuse the already detailed materials for the project's existing tree species.
            foreach(var r in tree.GetComponentsInChildren<Renderer>())
            {
                r.sharedMaterials=r.sharedMaterials.Select(m=>
                {
                    string original=m.name.Replace("Woodland ","");
                    string[] matches=AssetDatabase.FindAssets("t:Material",new[]{"Assets/Chapter2/Materials"});
                    return matches.Select(AssetDatabase.GUIDToAssetPath).Select(AssetDatabase.LoadAssetAtPath<Material>)
                        .FirstOrDefault(a=>a.name.StartsWith(original+"_",StringComparison.Ordinal))??m;
                }).ToArray();
            }
        }
    }

    static void AddPlants()
    {
        var parent=Group("Undergrowth · fern grass shrub flower pockets",scenery);
        string fern="Assets/Hipernt/Pine Pack/Prefabs/Plant2.prefab";
        string flower="Assets/Hipernt/Pine Pack/Prefabs/PlantFlower.prefab";
        string shrub="Assets/GreenForest/Prefabs/Bush.prefab";
        var grassMesh=BuildGrass();
        var grassMat=MaterialAsset("Fine forest grass",Shader.Find("Universal Render Pipeline/Lit"));
        grassMat.SetTexture("_BaseMap",null);
        grassMat.SetColor("_BaseColor",new Color(.34f,.39f,.17f));
        grassMat.SetFloat("_Smoothness",.05f);grassMat.SetFloat("_AlphaClip",0);
        grassMat.SetFloat("_Cull",0);grassMat.DisableKeyword("_ALPHATEST_ON");EditorUtility.SetDirty(grassMat);
        int plantCount=0;
        // Cluster centres stay along the sides; scattered gaps make the edge feel natural.
        for(int cluster=0;cluster<72;cluster++)
        {
            float side=cluster%2==0?-1:1;
            float z=Range(-18,24), inner=side<0?5.4f:3.9f;
            var centre=new Vector3(side*Range(inner,18.5f),0,z);
            for(int j=0;j<11;j++)
            {
                var p=centre+new Vector3(Range(-2.1f,2.1f),0,Range(-2,2));
                if(!PlantAllowed(p))continue;
                if(j<5)
                {
                    var g=new GameObject("Grass clump "+plantCount++,typeof(MeshFilter),typeof(MeshRenderer));
                    g.transform.SetParent(parent,false);g.transform.position=new Vector3(p.x,GroundY(p)-.012f,p.z);
                    g.transform.rotation=Quaternion.Euler(0,Range(0,360),0);
                    g.transform.localScale=Vector3.one*Range(.55f,1.3f);
                    g.GetComponent<MeshFilter>().sharedMesh=grassMesh;g.GetComponent<Renderer>().sharedMaterial=grassMat;
                    g.GetComponent<Renderer>().shadowCastingMode=ShadowCastingMode.Off;
                }
                else
                {
                    bool isFlower=j==10&&cluster%3==0;
                    var plant=Place(isFlower?flower:fern,(isFlower?"Wildflower ":"Fern ")+plantCount++,parent,p,
                        isFlower?Range(.23f,.43f):Range(.3f,.73f));
                    foreach(var r in plant.GetComponentsInChildren<Renderer>())r.shadowCastingMode=ShadowCastingMode.Off;
                }
            }
            if(cluster%2==0&&PlantAllowed(centre))Place(shrub,"Low shrub "+cluster,parent,centre,Range(.65f,1.2f));
        }
        // Small readable flower groups in the opening view, with uneven spacing.
        foreach(var centre in new[]{new Vector3(-5.6f,0,-11),new Vector3(3.8f,0,-9),new Vector3(-5.4f,0,-2),new Vector3(4.4f,0,3)})
            for(int i=0;i<7;i++)
            {
                var p=centre+new Vector3(Range(-.6f,.6f),0,Range(-.65f,.65f));
                if(PlantAllowed(p))Place(flower,"Pathside wildflower",parent,p,Range(.25f,.43f));
            }
        Debug.Log("[Chapter2 forest] Ground cover clumps: "+plantCount);
        parent.gameObject.AddComponent<Chapter2UnderstoryInstances>();
    }

    static bool PlantAllowed(Vector3 p)
    {
        if(p.x>-4.9f&&p.x<3.2f&&p.z<16)return false;
        if(new Vector2(p.x,p.z-10).magnitude<5.5f)return false;
        if(new Vector2(p.x,p.z).magnitude<5.3f)return false;
        if(homes.Any(h=>DistanceXZ(p,h)<1.85f))return false;
        return !trunks.Any(t=>DistanceXZ(p,t)<.45f);
    }
    static float DistanceXZ(Vector3 a,Vector3 b)=>Vector3.ProjectOnPlane(a-b,Vector3.up).magnitude;

    static void AddForestDebris()
    {
        var parent=Group("Forest floor · stones roots fallen wood",scenery);
        for(int i=0;i<65;i++)
        {
            var p=new Vector3((i%2==0?-1:1)*Range(4.5f,18),0,Range(-17,23));
            if(!PlantAllowed(p))continue;
            var rock=Place("Assets/Rock_pack/prefab/Rock_0"+(1+i%4)+".prefab","Weathered stone "+i,parent,p,Range(.09f,.42f));
            rock.transform.position-=Vector3.up*.025f;
        }
        for(int i=0;i<8;i++)
        {
            var p=trunks[i]+new Vector3(i%2==0?-.7f:.7f,0,.25f);
            Place("Assets/GreenForest/Prefabs/Root"+(1+i%4)+".prefab","Exposed tree root "+i,parent,p,Range(.18f,.34f));
        }
        foreach(var p in new[]{new Vector3(-8,0,-1.8f),new Vector3(9.2f,0,5),new Vector3(-11,0,14)})
            Place("Assets/GreenForest/Prefabs/CutedTree1.prefab","Old fallen branch",parent,p,.45f);
    }

    static void AddPeople(Chapter2Controller c)
    {
        var parent=Group("Background people · local patrols",c.dayGroup.transform);
        for(int i=0;i<homes.Length;i++)
        {
            bool police=i>=3;
            var source=police?c.officer:c.workers[i%c.workers.Length];
            var model=i==0?Chapter2ChildNPCAuthoring.LoadChild():source.gameObject;
            var g=Object.Instantiate(model,parent);g.name=i==0?Chapter2ChildNPCAuthoring.ChildName:police?"樹旁巡察警察 "+(i-2):"林間族人 "+(i+1);
            foreach(var b in g.GetComponentsInChildren<MonoBehaviour>(true))Object.DestroyImmediate(b);
            foreach(var col in g.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(col);
            // Ambient officers do not inherit the story rifle, muzzle flash, or targets.
            foreach(var t in g.GetComponentsInChildren<Transform>(true).Where(t=>t.name.Contains("步槍")||t.name.Contains("Rifle")||t.name.Contains("Muzzle")).ToArray())
                if(t)Object.DestroyImmediate(t.gameObject);
            foreach(var t in g.GetComponentsInChildren<Transform>(true))GameObjectUtility.RemoveMonoBehavioursWithMissingScript(t.gameObject);
            g.transform.position=homes[i]+Vector3.up*source.transform.position.y;
            var actor=g.AddComponent<Chapter2Actor>();actor.police=police;
            Vector3 direction=i%2==0?Vector3.right:Vector3.left;actor.facing=direction;
            var npc=g.AddComponent<Chapter2AmbientNPC>();npc.chapter=c;
            npc.patrolOffset=new Vector3(i%2==0?-1.15f:1.15f,0,.55f);
            npc.watchDirection=direction;npc.pauseSeconds=5+i*.9f;npc.phaseOffset=i*2.3f;
            foreach(var skin in g.GetComponentsInChildren<SkinnedMeshRenderer>())
            {
                skin.updateWhenOffscreen=false;
                // These high-resolution source people are small background figures.
                // Avoid rendering every skin again into all four shadow cascades.
                skin.shadowCastingMode=ShadowCastingMode.Off;
            }
        }
    }

    static Mesh BuildGrass()
    {
        var v=new List<Vector3>();var uv=new List<Vector2>();var triangles=new List<int>();
        var bladeRandom=new System.Random(771);
        for(int i=0;i<32;i++)
        {
            float a=(float)bladeRandom.NextDouble()*Mathf.PI*2;
            float radius=Mathf.Sqrt((float)bladeRandom.NextDouble())*.32f;
            Vector3 root=new Vector3(Mathf.Sin(a)*radius,0,Mathf.Cos(a)*radius);
            float height=.16f+(float)bladeRandom.NextDouble()*.29f,width=.008f+(float)bladeRandom.NextDouble()*.012f;
            Vector3 right=new Vector3(Mathf.Cos(a),0,-Mathf.Sin(a))*width;
            Vector3 lean=new Vector3(Mathf.Sin(a),0,Mathf.Cos(a))*(.07f+(float)bladeRandom.NextDouble()*.17f);
            int n=v.Count;
            for(int j=0;j<=3;j++)
            {
                float u=j/3f;Vector3 point=root+Vector3.up*height*u+lean*u*u;
                v.Add(point-right*(1-u*.97f));v.Add(point+right*(1-u*.97f));
                uv.Add(new Vector2(0,u));uv.Add(new Vector2(1,u));
                if(j<3){int k=n+j*2;triangles.AddRange(new[]{k,k+2,k+1,k+1,k+2,k+3});}
            }
        }
        string path=Root+"Geometry/FineGrass.asset";var mesh=AssetDatabase.LoadAssetAtPath<Mesh>(path);
        bool created=!mesh;if(created)mesh=new Mesh{name="FineGrass"};else mesh.Clear();
        mesh.name="FineGrass";mesh.SetVertices(v);mesh.SetUVs(0,uv);mesh.SetTriangles(triangles,0);
        mesh.RecalculateNormals();mesh.RecalculateTangents();mesh.RecalculateBounds();
        if(created)AssetDatabase.CreateAsset(mesh,path);else EditorUtility.SetDirty(mesh);
        return mesh;
    }

    static GameObject Place(string path,string name,Transform parent,Vector3 p,float height)
    {
        var source=AssetDatabase.LoadAssetAtPath<GameObject>(path);
        if(!source)throw new InvalidOperationException("Missing forest source: "+path);
        var g=Object.Instantiate(source,parent);g.name=name;
        foreach(var b in g.GetComponentsInChildren<MonoBehaviour>(true))Object.DestroyImmediate(b);
        foreach(var t in g.GetComponentsInChildren<Transform>(true))GameObjectUtility.RemoveMonoBehavioursWithMissingScript(t.gameObject);
        foreach(var c in g.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(c);
        g.transform.position=Vector3.zero;g.transform.rotation=Quaternion.Euler(0,Range(0,360),0);
        var renderers=g.GetComponentsInChildren<Renderer>();
        Bounds bounds=BoundsOf(renderers);g.transform.localScale*=height/Mathf.Max(.001f,bounds.size.y);
        bounds=BoundsOf(renderers);g.transform.position=new Vector3(p.x,GroundY(p)-bounds.min.y-.02f,p.z);
        foreach(var r in renderers){r.sharedMaterials=r.sharedMaterials.Select(Convert).ToArray();r.receiveShadows=true;}
        foreach(var lod in g.GetComponentsInChildren<LODGroup>())lod.RecalculateBounds();
        return g;
    }
    static Bounds BoundsOf(Renderer[] renderers)
    {Bounds b=renderers[0].bounds;foreach(var r in renderers)b.Encapsulate(r.bounds);return b;}
    static Material Convert(Material source)
    {
        if(!source)throw new InvalidOperationException("Forest source has an empty material slot.");
        if(converted.TryGetValue(source,out var m))return m;
        m=MaterialAsset("Woodland "+source.name,Shader.Find("Universal Render Pipeline/Lit"));
        var tex=source.HasProperty("_BaseMap")?source.GetTexture("_BaseMap"):source.mainTexture;
        if(tex)m.SetTexture("_BaseMap",Texture(AssetDatabase.GetAssetPath(tex),false));
        Texture normal=source.HasProperty("_BumpMap")?source.GetTexture("_BumpMap"):null;
        if(!normal&&tex)
        {
            string p=AssetDatabase.GetAssetPath(tex), folder=Path.GetDirectoryName(p).Replace('\\','/');
            string candidate=p.Replace(".png","_normal.png");
            if(!File.Exists(candidate))candidate=folder+"/normal_specular.png";
            normal=AssetDatabase.LoadAssetAtPath<Texture2D>(candidate);
        }
        if(normal){m.SetTexture("_BumpMap",Texture(AssetDatabase.GetAssetPath(normal),true));m.EnableKeyword("_NORMALMAP");m.SetFloat("_BumpScale",.45f);}
        bool bark=source.name.IndexOf("bark",StringComparison.OrdinalIgnoreCase)>=0||source.name.IndexOf("rock",StringComparison.OrdinalIgnoreCase)>=0;
        m.SetColor("_BaseColor",bark?Color.white:new Color(.9f,.94f,.79f));
        m.SetFloat("_Smoothness",.08f);m.SetFloat("_Cull",bark?2:0);m.SetFloat("_AlphaClip",bark?0:1);m.SetFloat("_Cutoff",.38f);
        if(bark)m.DisableKeyword("_ALPHATEST_ON");else m.EnableKeyword("_ALPHATEST_ON");
        EditorUtility.SetDirty(m);converted[source]=m;return m;
    }
    static Material MaterialAsset(string name,Shader shader)
    {
        string path=Root+"Materials/"+name.Replace('/','_')+".mat";
        var m=AssetDatabase.LoadAssetAtPath<Material>(path);
        if(!m){m=new Material(shader){name=name};AssetDatabase.CreateAsset(m,path);}
        m.shader=shader;m.enableInstancing=true;return m;
    }
    static Texture2D Texture(string source,bool normal)
    {
        // Scoped copies preserve import settings used by the original chapters.
        string id=AssetDatabase.AssetPathToGUID(source);
        if(id.Length<8)throw new InvalidOperationException("Missing forest texture: "+source);
        string path=source.StartsWith(Root,StringComparison.Ordinal)?source:Root+"Textures/"+id.Substring(0,8)+"_"+Path.GetFileName(source);
        if(!File.Exists(path)){File.Copy(source,path);AssetDatabase.ImportAsset(path);}
        var importer=(TextureImporter)AssetImporter.GetAtPath(path);
        bool isData=source.Contains("_ao_")||source.Contains("_rough_");int size=source.Contains("_4k")?4096:2048;
        if(importer.textureType!=(normal?TextureImporterType.NormalMap:TextureImporterType.Default)||importer.anisoLevel!=16||importer.maxTextureSize!=size)
        {
            importer.textureType=normal?TextureImporterType.NormalMap:TextureImporterType.Default;
            importer.sRGBTexture=!normal&&!isData;importer.mipmapEnabled=true;importer.filterMode=FilterMode.Trilinear;
            importer.anisoLevel=16;importer.maxTextureSize=size;importer.wrapMode=TextureWrapMode.Repeat;
            importer.alphaSource=TextureImporterAlphaSource.FromInput;importer.alphaIsTransparency=!normal;
            importer.textureCompression=TextureImporterCompression.CompressedHQ;importer.SaveAndReimport();
        }
        return AssetDatabase.LoadAssetAtPath<Texture2D>(path);
    }
    static Transform Group(string name,Transform parent){var t=new GameObject(name).transform;t.SetParent(parent,false);return t;}
    static float GroundY(Vector3 p)=>ground.Raycast(new Ray(new Vector3(p.x,60,p.z),Vector3.down),out var hit,120)?hit.point.y:0;
    static float Range(float min,float max)=>Mathf.Lerp(min,max,(float)random.NextDouble());
}
